"""Deterministic Ansible bootstrap inventory export for desired nodes."""

from __future__ import annotations

from dataclasses import dataclass
import json
import re
from typing import Any, Iterable

import yaml


ANSIBLE_HOSTS_INTENT_SCHEMA_VERSION = "1.0"
ELIGIBLE_NODE_LIFECYCLES = frozenset({"planned", "approved", "active"})
# service_host represents a host whose eventual Nautobot object may be either a
# device or a virtual machine, so it is eligible for bootstrap discovery too.
ELIGIBLE_NODE_TYPES = frozenset({"device", "virtual_machine", "service_host"})


@dataclass(frozen=True)
class HostsIntentExport:
    """Serializable hosts intent export payload."""

    summary: dict[str, Any]
    inventory: dict[str, Any]
    hosts: list[dict[str, Any]]
    skipped: list[dict[str, Any]]

    def as_dict(self) -> dict[str, Any]:
        return {
            "summary": self.summary,
            "inventory": self.inventory,
            "hosts": self.hosts,
            "skipped": self.skipped,
        }


def export_hosts_intent(nodes: Iterable[Any], *, include_skipped: bool = True) -> HostsIntentExport:
    """Return a deterministic minimal Ansible inventory from desired nodes."""

    hosts: list[dict[str, Any]] = []
    skipped: list[dict[str, Any]] = []
    group_members: dict[str, set[str]] = {"ssh_hosts": set()}
    total_nodes = 0
    exported_nodes = 0
    skipped_nodes = 0
    skipped_group_count = 0

    for node in sorted(list(nodes), key=_node_sort_key):
        total_nodes += 1
        expected_spec = _mapping(getattr(node, "expected_spec", None))
        node_skip_reasons = _node_skip_reasons(node)
        endpoint = _select_mdns_endpoint(node, expected_spec)
        if endpoint is None:
            node_skip_reasons.append("missing_mdns_name")

        inventory_hostname = _inventory_hostname(node, expected_spec)
        if not _valid_inventory_hostname(inventory_hostname):
            node_skip_reasons.append("invalid_inventory_hostname")

        if node_skip_reasons:
            skipped_nodes += 1
            if include_skipped:
                skipped.append(_node_skip_entry(node, endpoint, node_skip_reasons))
            continue

        exported_nodes += 1
        host_vars = _host_vars(node, endpoint, expected_spec)
        hosts.append(
            {
                "inventory_hostname": inventory_hostname,
                "desired_node": _text(getattr(node, "name", None)),
                "desired_node_id": _pk(node),
                "desired_node_slug": _text(getattr(node, "slug", None)),
                "desired_endpoint": _text(getattr(endpoint, "name", None)),
                "desired_endpoint_id": _pk(endpoint),
                "mdns_hostname": _text(getattr(endpoint, "mdns_name", None)),
                "host_vars": host_vars,
            }
        )
        group_members["ssh_hosts"].add(inventory_hostname)

        for group in _list(expected_spec.get("ansible_groups")):
            raw_group = _text(group)
            normalized_group = _normalize_group_name(raw_group)
            if not normalized_group:
                skipped_group_count += 1
                if include_skipped:
                    skipped.append(_group_skip_entry(node, raw_group, "invalid_ansible_group"))
                continue
            group_members.setdefault(normalized_group, set()).add(inventory_hostname)

    hosts.sort(key=lambda item: item["inventory_hostname"])
    skipped.sort(key=_skip_sort_key)
    inventory = _inventory(hosts, group_members)
    summary = {
        "schema_version": ANSIBLE_HOSTS_INTENT_SCHEMA_VERSION,
        "total_nodes": total_nodes,
        "exported_hosts": len(hosts),
        "exported_nodes": exported_nodes,
        "skipped_nodes": skipped_nodes,
        "skipped_groups": skipped_group_count,
        "skipped_details": len(skipped),
        "groups": sorted(group for group, members in group_members.items() if members),
    }
    return HostsIntentExport(summary=summary, inventory=inventory, hosts=hosts, skipped=skipped)


def hosts_intent_payload(
    export: HostsIntentExport,
    *,
    generated_at: str,
    job_result_id: str | None = None,
) -> dict[str, Any]:
    """Return a stable, machine-readable hosts intent export payload."""

    return {
        "schema_version": ANSIBLE_HOSTS_INTENT_SCHEMA_VERSION,
        "generated_at": generated_at,
        "job_result_id": job_result_id,
        "summary": export.summary,
        "inventory": export.inventory,
        "hosts": export.hosts,
        "skipped": export.skipped,
    }


def render_hosts_intent_yml(
    export: HostsIntentExport,
    *,
    generated_at: str,
    job_result_id: str | None = None,
) -> str:
    """Return an Ansible YAML inventory for bootstrap collection."""

    lines = [
        "# Generated by Nautobot Intent Catalog",
        f"# schema_version: {ANSIBLE_HOSTS_INTENT_SCHEMA_VERSION}",
        f"# generated_at: {generated_at}",
    ]
    if job_result_id:
        lines.append(f"# job_result_id: {job_result_id}")
    lines.append(yaml.safe_dump(export.inventory, sort_keys=False, default_flow_style=False).rstrip())
    return "\n".join(lines) + "\n"


def render_hosts_intent_json(
    export: HostsIntentExport,
    *,
    generated_at: str,
    job_result_id: str | None = None,
) -> str:
    """Return a deterministic JSON representation of a hosts intent export."""

    return json.dumps(
        hosts_intent_payload(export, generated_at=generated_at, job_result_id=job_result_id),
        sort_keys=True,
        ensure_ascii=True,
        indent=2,
    ) + "\n"


def _node_skip_reasons(node: Any) -> list[str]:
    reasons = []
    lifecycle = _text(getattr(node, "lifecycle", None))
    node_type = _text(getattr(node, "node_type", None))
    if lifecycle not in ELIGIBLE_NODE_LIFECYCLES:
        reasons.append("node_lifecycle_not_exportable")
    if node_type not in ELIGIBLE_NODE_TYPES:
        reasons.append("node_type_not_exportable")
    return reasons


def _select_mdns_endpoint(node: Any, expected_spec: dict[str, Any]) -> Any | None:
    endpoints = [endpoint for endpoint in _endpoints(node) if _text(getattr(endpoint, "mdns_name", None))]
    if not endpoints:
        return None

    preferred_name = _text(expected_spec.get("ansible_mdns_endpoint"))
    if preferred_name:
        for endpoint in sorted(endpoints, key=_endpoint_sort_key):
            if _text(getattr(endpoint, "name", None)) == preferred_name:
                return endpoint

    for endpoint_type in ("primary", "management"):
        matching = [
            endpoint
            for endpoint in endpoints
            if _text(getattr(endpoint, "endpoint_type", None)) == endpoint_type
        ]
        if matching:
            return sorted(matching, key=_endpoint_sort_key)[0]

    return sorted(endpoints, key=_endpoint_sort_key)[0]


def _inventory_hostname(node: Any, expected_spec: dict[str, Any]) -> str:
    return _text(expected_spec.get("ansible_host_name")) or _text(getattr(node, "slug", None))


def _host_vars(node: Any, endpoint: Any, expected_spec: dict[str, Any]) -> dict[str, Any]:
    host_vars = {
        "mdns_hostname": _text(getattr(endpoint, "mdns_name", None)),
        "nintent_inventory_stage": "reserved_name",
        "nintent_desired_node": _text(getattr(node, "name", None)),
        "nintent_desired_node_slug": _text(getattr(node, "slug", None)),
        "nintent_desired_node_id": _pk(node),
        "nintent_desired_endpoint": _text(getattr(endpoint, "name", None)),
        "nintent_desired_endpoint_id": _pk(endpoint),
        "name_reserved_only": True,
    }
    host_os = _text(expected_spec.get("host_os")) or _text(expected_spec.get("os"))
    if host_os:
        host_vars["host_os"] = host_os
    return host_vars


def _inventory(hosts: list[dict[str, Any]], group_members: dict[str, set[str]]) -> dict[str, Any]:
    host_vars_by_name = {host["inventory_hostname"]: host["host_vars"] for host in hosts}
    children = {}
    for group in sorted(group_members):
        members = sorted(group_members[group])
        if not members:
            continue
        group_hosts = {}
        for member in members:
            group_hosts[member] = host_vars_by_name[member] if group == "ssh_hosts" else {}
        children[group] = {"hosts": group_hosts}
    return {"all": {"children": children}}


def _endpoints(node: Any) -> list[Any]:
    value = getattr(node, "desired_endpoints", None)
    if value is None:
        return []
    all_method = getattr(value, "all", None)
    if callable(all_method):
        return list(all_method())
    if isinstance(value, list | tuple):
        return list(value)
    return []


def _node_skip_entry(node: Any, endpoint: Any | None, reasons: list[str]) -> dict[str, Any]:
    return {
        "item_type": "desired_node",
        "desired_node": _text(getattr(node, "name", None)),
        "desired_node_id": _pk(node),
        "desired_node_slug": _text(getattr(node, "slug", None)),
        "desired_endpoint": _text(getattr(endpoint, "name", None)),
        "desired_endpoint_id": _pk(endpoint),
        "reasons": sorted(set(reasons)),
    }


def _group_skip_entry(node: Any, group: str, reason: str) -> dict[str, Any]:
    return {
        "item_type": "ansible_group",
        "desired_node": _text(getattr(node, "name", None)),
        "desired_node_id": _pk(node),
        "desired_node_slug": _text(getattr(node, "slug", None)),
        "group": group,
        "reasons": [reason],
    }


def _normalize_group_name(value: str) -> str:
    if not value:
        return ""
    normalized = re.sub(r"[^A-Za-z0-9_]+", "_", value).strip("_")
    if not re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", normalized):
        return ""
    return normalized


def _valid_inventory_hostname(value: str) -> bool:
    return bool(value) and not bool(re.search(r"[\s:]", value))


def _node_sort_key(node: Any) -> tuple[str, str]:
    return (_text(getattr(node, "slug", None)), _text(getattr(node, "name", None)))


def _endpoint_sort_key(endpoint: Any) -> tuple[str, str]:
    return (_text(getattr(endpoint, "endpoint_type", None)), _text(getattr(endpoint, "name", None)))


def _skip_sort_key(entry: dict[str, Any]) -> tuple[str, str, str]:
    return (
        _text(entry.get("item_type")),
        _text(entry.get("desired_node_slug")),
        _text(entry.get("group") or entry.get("desired_endpoint")),
    )


def _mapping(value: Any) -> dict[str, Any]:
    return value if isinstance(value, dict) else {}


def _list(value: Any) -> list[Any]:
    return value if isinstance(value, list) else []


def _text(value: Any) -> str:
    if value is None:
        return ""
    return str(value).strip()


def _pk(obj: Any) -> str:
    if obj is None:
        return ""
    return str(getattr(obj, "pk", None) or getattr(obj, "id", None) or "")
